name: Update Spotify Top Track

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight (UTC)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-track:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout spotify-github-readme-updater repository
      uses: actions/checkout@v3
      with:
        path: updater-repo

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: updater-repo

    - name: Run script to update README
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: node updater-repo/script.js

    - name: Checkout profile repository
      uses: actions/checkout@v3
      with:
        repository: Vyshnav12/Vyshnav12
        token: ${{ secrets.PAT }}
        path: profile-repo

    - name: Copy updated README to profile repository
      run: |
        cp updater-repo/README.md profile-repo/README.md
        cd profile-repo
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add README.md
        git commit -m "Update README with the most played Spotify track" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
